### ISSUE TITLE
Parameter text gets deleted unless using enter

### ISSUE THREAD

**Issue by markhalonen** [relinc/SurePulseDataProcessor#16]

**Comment by bhalonen** [comment]
The doubled down on this one. They would also like tabs to switch between lines in sample creation.
![image](https://user-images.githubusercontent.com/7853544/32520408-dfdebf42-c3dd-11e7-9594-94225019dad9.png)

**Comment by markhalonen** [comment]
> They would also like tabs to switch between lines in sample creation.
Not sure what this means. When I'm on the sample creation page, I can use tab to switch between Name, Length, Diameter, etc. So you mean somewhere else?

**Comment by bhalonen** [comment]
On the extra parameters tab

**Comment by bhalonen** [comment]
In the table pictured

**Comment by markhalonen** [comment]
So the tab should "switch between lines". I'm assuming this means navigate to the next table cell available, from left-to-right then top-to-bottom.

**Comment by bhalonen** [comment]
Yeah. Poorly phrased, Write it how you would want tab to work. They actually use that feature.
