### ISSUE TITLE
Arrows on filter adjustment

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulseDataProcessor#19]
Arrows to adjust filter size.
![image](https://user-images.githubusercontent.com/7853544/32520595-891468fa-c3de-11e7-8288-92453664f388.png)

**Comment by markhalonen** [comment]
It seems we should be able to calculate a rational step size for the arrows here that depends on the total time length of the data. So if the data is 2 seconds long, the step size should be ??

**Comment by bhalonen** [comment]
Could do it based on max frequency (2Hz for this case) to Nyquist (twice the sampling rate) and make 100 gradations between them, round to a number ending in a zero.

**Comment by bhalonen** [comment]
If there is a really high sampling rate, that should matter as well.

**Comment by bhalonen** [comment]
Actually- Luke requested that it works like Pico. If that is at all possible.

**Comment by markhalonen** [comment]
I was able to get pico up and running with some sample data. Looks like they go something like
1,2,3,4,5,6,7,8,9, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800, 900KHz
And then the same pattern with MHz

Should be able to clone

**Comment by bhalonen** [comment]
Add the same arrows to the "Global filter" in analysis.

**Comment by markhalonen** [comment]
The PR's are spread across the different repos, SurePulseDataProcessor, SurePulseDataViewer, SPLibraries
