### ISSUE TITLE
Zoom in fitter

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulseDataProcessor#20]
Luke wants a zoom in fitter.
![image](https://user-images.githubusercontent.com/7853544/32520716-fb07d0b4-c3de-11e7-95fb-27da38935ce8.png)

**Comment by markhalonen** [comment]
So just a visual zoom functionality? It allows for picking start/end.

**Comment by bhalonen** [comment]
Yeah, I'm not entirely sure of the use case, but he was pretty explicit.

**Comment by markhalonen** [comment]
So, this one is fun. It required changes across 4 repos:

- Fitter (most of the code): [PR](https://github.com/relinc/SUREPulseFitter/pull/2)
- Processor [PR](https://github.com/relinc/SurePulseDataProcessor/pull/32)
- SPLibraries [PR](https://github.com/relinc/SPLibraries/pull/14)
- ImageCorrelation [PR](https://github.com/relinc/SUREPulseImageCorrelation/pull/5)

All the changes are on branch `fitter-zoom` for all repos.

Regarding features, I only implemented setting the zoom on the data plot, not the residual. The residual updates the range (on the X axis only), but you can't click and drag on it to set the zoom box. If this is desired it can be implemented.

**Comment by markhalonen** [comment]
You can test it by running SUREPulseFitter directly. There is a "Load Data" button in the top left where you can load data. This is a standalone application separate from SurePulse. Perhaps it could be used somewhere else?

**Comment by markhalonen** [comment]
[003-Lagrange Strain.txt](https://github.com/relinc/SurePulseDataProcessor/files/1464000/003-Lagrange.Strain.txt)

Ideally you'd find some random data to use, but here's the data I used
