### ISSUE TITLE
Toggling samples in causes strain video to not load correctly

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulseDataProcessor#21]
When viewing video and stress-strain, toggling between samples does not result in correct behavior.
![image](https://user-images.githubusercontent.com/7853544/32521411-78a410e4-c3e1-11e7-8f01-b9f0f2589da5.png)

**Comment by markhalonen** [comment]
Video explaining the bug (I think): https://youtu.be/OZmjIrtO4nE

**Comment by bhalonen** [comment]
Can you get me some example data for this one? Thanks.

**Comment by markhalonen** [comment]
[SurePulseSmaller.zip](https://github.com/relinc/SurePulseDataProcessor/files/1467608/SurePulseSmaller.zip)

**Comment by markhalonen** [comment]
[Images.zip](https://github.com/relinc/SurePulseDataProcessor/files/1469488/Images.zip)

**Comment by markhalonen** [comment]
[SurePulse copy.zip](https://github.com/relinc/SurePulseDataProcessor/files/1469515/SurePulse.copy.zip)
