### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulseDataProcessor#24]
BibTex
```
@misc{SUREPulse,
  Author = {{Halonen, B., Halonen, M., REL Inc.}},
  title = {{SURE-Pulse}},
  year = {2015},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/relinc/SurePulseDataProcessor}},
  commit = {4f57d6a0e4c030202a07a60bc1bb1ed1544bf679} 
} 
```

Change to current commit?
Plain Text:

Halonen, B., Halonen, M., REL Inc. SURE-Pulse. https://github.com/relinc/SurePulseDataProcessor, 2015.

**Comment by bhalonen** [comment]
Or should it just reference REL Inc.?

**Comment by bhalonen** [comment]
Place a window on the front page and at export to make it easy to cite.

**Comment by markhalonen** [comment]
> Or should it just reference REL Inc.?

Sounds like a question for REL.

**Comment by bhalonen** [comment]
I asked them, Adam said to reference REL for now.

**Comment by markhalonen** [comment]
![image](https://user-images.githubusercontent.com/7853605/32615950-18c7454c-c53f-11e7-9857-ea5157efd535.png)

**Comment by bhalonen** [comment]
Leave it like that for now. Will review with them.

**Comment by bhalonen** [comment]
Didn't mean to close.

**Comment by bhalonen** [comment]
Ok, this looks to be a good place to find the commits that matter. Still learning how to properly use Github.
