### ISSUE TITLE
Add tutorial button that has links to youtube videos

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulseDataProcessor#30]
Front page.

**Comment by markhalonen** [comment]
I'm going to branch this one off `references`, as I know there will be merge conflicts if I don't. I believe git will handle this like a champ if we merge `references`, then the new branch `tutorials`

**Comment by markhalonen** [comment]
![image](https://user-images.githubusercontent.com/7853605/32635407-43874298-c57e-11e7-8534-beb2a7fefbf5.png)

Interface is getting a little clunky, @bhalonen any thoughts on where to put tutorials button? I'm assuming it will be a pop up window with all the links

**Comment by markhalonen** [comment]
I was thinking maybe move "Shot Caller" below "Analyze Results" and replacing it with "Tutorials"

**Comment by markhalonen** [comment]
Current look:
![image](https://user-images.githubusercontent.com/7853605/32636999-70834588-c585-11e7-956a-164020917547.png)

**Comment by bhalonen** [comment]
Make this pull request now. I could go through and make and merge it myself, but that is probably a bad idea.

**Comment by markhalonen** [comment]
Ok there is a [PR](https://github.com/relinc/SurePulseDataProcessor/pull/34) for the processor and a [PR](https://github.com/relinc/SurePulseDataProcessor/pull/34) for SPLibaries
