### ISSUE TITLE
Summary of advanced options

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulseDataProcessor#46]
Check out this section for adding it as an explanation of defaults to the advanced settings tab.

A little pop-up will do.

Default settings:
Lagrangian strain is chosen for the output strain as it can be easily transformed to true strain. Lagrangian strain is defined with respect to the initial length of the the object, which is the usual for mechanics.

Eulerian strain is chosen for video as it allows for easy display of a deformed strain field. This allows for easier visualization of how the material is deforming.

Scale factor is the factor that displacement results are downsized. A larger factor gives faster, less accurate results.

Interpolation, cubic keys interpolation is defaulted to as it saves time on computation without a large degradation in quality. Biquintic interpolation is more accurate, but takes longer to compute.

Threads is the number of threads the correlation job is broken into. The more threads, the faster the job completes, however, less resources are left for using the computer while computation is being done.

Subregion is defaulted to circle. In the future, rectangular subregions may be offered. The subregion is the shape small area tracked by the correlation.

Radius sub is the radius of the subregion being tracked. This must correspond to have a few identifiable markers in the radius.

DIC Config has three options. NO_UPDATE never removes points from being tracked. If the object under analysis remains cohesive the entire time, this option makes sense. 

Default output is chosen to be e1 or the first principle strain. This lowers the need for perfect alignment of sample in camera.

**Comment by markhalonen** [comment]
What is the last one supposed to be for? 
> Default output is chosen to be e1 or the first principle strain. This lowers the need for perfect alignment of sample in camera.

"CSV Out" or "Video/Img Out"?
![image](https://user-images.githubusercontent.com/7853605/33464438-363485ae-d610-11e7-95d9-5785dbb6abd3.png)

**Comment by markhalonen** [comment]
I assumed it's for "Video/Img Out" and created the PR
