### ISSUE TITLE
Video summarizing how to use DIC.

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulseDataProcessor#47]
A quick summary of how to use DIC, add a link to the tutorial section.

**Comment by bhalonen** [comment]
I made the video, but I must suck at uploading. I'll have a link to target.

**Comment by bhalonen** [comment]
https://youtu.be/ed99pmCts28

**Comment by markhalonen** [comment]
I requested to Kent to upload this to REL's account [where all the other tutorial videos are](https://www.youtube.com/watch?v=sgcpSif-VFY&list=PLeFdq4ZC_eAttrgIYoYX5FIPbQCaKxPBn)

**Comment by bhalonen** [comment]
Sounds good. I thought that sounded more legitimate.
